"""API 路由汇总（在 main.py 以 /api 前缀挂载；WS 路由单独挂在根路径）。"""

from fastapi import APIRouter

from app.api import (
    admin_llm,
    admin_settings,
    auth,
    chat_agent,
    chat_bots,
    concepts,
    daily,
    desktop_runtime,
    disciplines,
    download_client,
    evidence,
    experiment_backends,
    experiments,
    export,
    gates,
    health,
    highlights,
    hypotheses,
    ideas,
    ingest,
    integration_tokens,
    interdisciplinary,
    libraries,
    library,
    literature_discovery,
    literature_sources,
    manuscripts,
    mcp_meta,
    mcp_servers,
    notes,
    obsidian_vault,
    onboarding,
    paper_assets,
    papers,
    plugins,
    presentations,
    projects,
    publications,
    resources,
    search,
    shelf,
    ssh_credentials,
    structured_content,
    summary_batches,
    tts,
    users_profile,
    voyages,
    wiki,
    zotero_local,
)

api_router = APIRouter()
api_router.include_router(summary_batches.router)
api_router.include_router(desktop_runtime.router)
api_router.include_router(health.router)
api_router.include_router(chat_agent.router)
api_router.include_router(auth.router)
api_router.include_router(chat_bots.router)
api_router.include_router(users_profile.router)
api_router.include_router(projects.router)
api_router.include_router(gates.router)
api_router.include_router(voyages.router)
api_router.include_router(hypotheses.router)
api_router.include_router(admin_llm.router)
api_router.include_router(admin_settings.router)
api_router.include_router(papers.router)
api_router.include_router(library.router)
api_router.include_router(literature_discovery.router)
api_router.include_router(paper_assets.router)
api_router.include_router(structured_content.router)
api_router.include_router(libraries.router)
api_router.include_router(publications.router)
api_router.include_router(notes.router)
api_router.include_router(obsidian_vault.router)
api_router.include_router(highlights.router)
api_router.include_router(concepts.router)
api_router.include_router(ingest.router)
api_router.include_router(interdisciplinary.router)
api_router.include_router(interdisciplinary.suggestion_router)
api_router.include_router(integration_tokens.router)
api_router.include_router(wiki.router)
api_router.include_router(ideas.router)
api_router.include_router(search.router)
api_router.include_router(shelf.router)
api_router.include_router(daily.router)
api_router.include_router(download_client.router)
api_router.include_router(mcp_meta.router)
api_router.include_router(presentations.router)
api_router.include_router(ssh_credentials.router)
api_router.include_router(resources.router)
api_router.include_router(resources.credentials_router)
api_router.include_router(tts.router)
api_router.include_router(evidence.router)
api_router.include_router(experiments.router)
api_router.include_router(manuscripts.router)
api_router.include_router(export.router)
api_router.include_router(plugins.router)
api_router.include_router(mcp_servers.router)
api_router.include_router(experiment_backends.router)
api_router.include_router(disciplines.router)
api_router.include_router(literature_sources.router)
api_router.include_router(onboarding.router)
api_router.include_router(zotero_local.router)
